model:
  base_learning_rate: 5e-5
  target: cfm.models.diffusion.cfm_scale_cfg_distill_vcfg.CFM_MAA2_CFG
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    mel_dim: 20
    mel_length: 256
    first_stage_key: "mix_spec"
    cond_stage_key: "mix_video_feat"
    image_size: 64
    channels: 0 
    cond_stage_trainable: true   
    conditioning_key: crossattn
    monitor: val/loss_ema
    scale_factor: 0.18215
    use_ema: False
    model_ckpt_path: ckpt/v2a/reflow/last.ckpt

    scheduler_config: # 10000 warmup steps
      target: cfm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 1000 ]
        cycle_lengths: [ 10000000000000 ] 
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: cfm.modules.diffusionmodules.concatDiT.ChannelConcatDiT
      params:
        in_channels: 20
        context_dim: 768
        hidden_size: 576
        num_heads: 8
        depth: 4
        max_len: 1000

    first_stage_config:
      target: cfm.models.autoencoder1d.AutoencoderKL
      params:
        embed_dim: 20
        monitor: val/rec_loss
        ckpt_path: ckpt/maa2/trainae/ckpt/epoch=000032.ckpt
        ddconfig:
          double_z: true
          in_channels: 80
          out_ch: 80
          z_channels: 20
          kernel_size: 5
          ch: 384
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_layers:
          - 3
          down_layers:
          - 0
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    
    cond_stage_config: 
      target: cfm.modules.cond_stage.video_feat_encoder.Video_Feat_Encoder_NoPosembed
      params:
        origin_dim: 512
        embed_dim: 768
        seq_len: 40

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32 
    num_workers: 6
    wrap: True
    train:
      target: cfm.data.video_spec_maa2_reflow_mix_dataset.audio_video_spec_fullset_Dataset_Train
      params:
        dataset1:
          dataset_name: VGGSound
          reflow_dir: data/vggsound/reflow
          data_dir: data/vggsound
          video_dir: data/vggsound          
          split_txt_path: data/vggsound/split_txt_reflow

        feat_type: CAVP_feat
        sr: 16000
        duration: 8
        truncate: 131072
        fps: 4
        hop_len: 256

    validation:
      target: cfm.data.video_spec_maa2_reflow_mix_dataset.audio_video_spec_fullset_Dataset_Valid
      params:
        dataset1:
          dataset_name: VGGSound
          reflow_dir: data/vggsound/reflow
          data_dir: data/vggsound
          video_dir: data/vggsound          
          split_txt_path: data/vggsound/split_txt_reflow

        feat_type: CAVP_feat
        sr: 16000
        duration: 8
        truncate: 131072
        fps: 4
        hop_len: 256

checkpoint:
  save_every_n_epochs: 1


callback:
  logger_name: sound_logger
  target: cfm.logger_maa2.SoundLogger_concat_fullset
  params: 
    train_batch_frequency: 10000
    val_batch_frequency: 10000
    max_sound_num: 8
    sr: 16000
    fps: 4
    guidance_scale: 6.5

    vocoder_cfg:
      target: vocoder.bigvgan.models.VocoderBigVGAN
      params:
        ckpt_vocoder: ckpt/bigvnat
  


